# Generated by Django 6.0.4 on 2026-04-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldetail',
            name='distance_to_airport_km',
        ),
        migrations.RemoveField(
            model_name='hoteldetail',
            name='distance_to_top_attraction_km',
        ),
        migrations.RemoveField(
            model_name='hoteldetail',
            name='nearest_attraction_name',
        ),
    ]
