# Generated by Django 6.0.4 on 2026-04-26 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_analysis', '0002_remove_hoteldetail_distance_to_airport_km_and_more'),
        ('core', '0016_businessanalysisrequest_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructiondetail',
            name='equipment_pct',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='constructiondetail',
            name='license_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='constructiondetail',
            name='project_type',
            field=models.CharField(default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='advance_booking_pct',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='booking_profile',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='collateral_type',
            field=models.CharField(default='property', max_length=50),
        ),
        migrations.AddField(
            model_name='textiledetail',
            name='cert_type',
            field=models.CharField(default='gost', max_length=20),
        ),
        migrations.AddField(
            model_name='textiledetail',
            name='export_pct',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='textiledetail',
            name='factory_sqm',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='textiledetail',
            name='market_type',
            field=models.CharField(default='domestic', max_length=20),
        ),
        migrations.AddField(
            model_name='tradedetail',
            name='credit_line_needed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='tradedetail',
            name='stock_turnover',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tradedetail',
            name='suppliers_count',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(default='individual', max_length=50)),
                ('equipment_uzs', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('repeat_pct', models.IntegerField(default=40)),
                ('service_avg_price', models.DecimalField(decimal_places=0, default=150000, max_digits=15)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_detail', to='core.businessanalysisrequest')),
            ],
            options={
                'verbose_name': 'Xizmat tafsilotlari',
            },
        ),
    ]
