# Generated by Django 6.0.4 on 2026-04-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakeven_months', models.FloatField(default=0.0)),
                ('breakeven_revenue_uzs', models.BigIntegerField(default=0)),
                ('mc_profit_distribution', models.JSONField(default=list)),
                ('mc_mean_profit', models.BigIntegerField(default=0)),
                ('mc_std_profit', models.BigIntegerField(default=0)),
                ('mc_success_probability', models.FloatField(default=0.0)),
                ('roi_12mo', models.FloatField(default=0.0)),
                ('roi_36mo', models.FloatField(default=0.0)),
                ('cac_uzs', models.BigIntegerField(default=0)),
                ('ltv_uzs', models.BigIntegerField(default=0)),
                ('ltv_cac_ratio', models.FloatField(default=0.0)),
                ('gross_margin_pct', models.FloatField(default=0.0)),
                ('cash_flow_monthly_24', models.JSONField(default=list)),
                ('viability_score', models.FloatField(default=0.0)),
                ('ai_commentary', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('is_mock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_d', to='core.businessanalysisrequest')),
            ],
            options={
                'verbose_name': 'D Blok — Moliyaviy maqsadga muvofiqlik',
            },
        ),
    ]
