# Generated by Django 6.0.4 on 2026-04-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockEResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitors_300m', models.JSONField(default=list)),
                ('competitors_1km', models.JSONField(default=list)),
                ('entry_barriers', models.JSONField(default=list)),
                ('market_risk_score', models.FloatField(default=0.0)),
                ('market_risk_score_inv', models.FloatField(default=0.0)),
                ('district_churn_rate', models.FloatField(default=0.0)),
                ('recommendation_notes', models.TextField(blank=True)),
                ('ai_commentary', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('is_mock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_e', to='core.businessanalysisrequest')),
            ],
            options={
                'verbose_name': 'E Blok — Raqobat va risklar',
            },
        ),
    ]
