# Generated by Django 6.0.4 on 2026-04-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockBResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_forecast_12', models.JSONField(default=list)),
                ('monthly_forecast_36', models.JSONField(default=list)),
                ('confidence_low_12', models.JSONField(default=list)),
                ('confidence_high_12', models.JSONField(default=list)),
                ('revenue_p10', models.BigIntegerField(default=0)),
                ('revenue_p50', models.BigIntegerField(default=0)),
                ('revenue_p90', models.BigIntegerField(default=0)),
                ('seasonality_ramazon_boost_pct', models.FloatField(default=0.0)),
                ('seasonality_navro_boost_pct', models.FloatField(default=0.0)),
                ('seasonality_weekly', models.JSONField(default=list)),
                ('demand_score', models.FloatField(default=0.0)),
                ('ai_commentary', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('is_mock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_b', to='core.businessanalysisrequest')),
            ],
            options={
                'verbose_name': 'B Blok — Talab prognozi',
            },
        ),
    ]
