# Generated by Django 6.0.4 on 2026-04-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_score', models.FloatField(default=0.0)),
                ('hourly_footfall', models.JSONField(default=list)),
                ('daily_footfall', models.JSONField(default=list)),
                ('isochrone_demand_5min', models.IntegerField(default=0)),
                ('isochrone_demand_10min', models.IntegerField(default=0)),
                ('anchor_businesses', models.JSONField(default=list)),
                ('anchor_effect_score', models.FloatField(default=0.0)),
                ('competitors_300m', models.JSONField(default=list)),
                ('competitors_1km', models.JSONField(default=list)),
                ('ai_commentary', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('is_mock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_c', to='core.businessanalysisrequest')),
            ],
            options={
                'verbose_name': 'C Blok — Joylashuv razvedkasi',
            },
        ),
    ]
