# Generated by Django 6.0.4 on 2026-04-25 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=150, verbose_name='Biznes turi')),
                ('mcc_code', models.CharField(choices=[('5812', 'Restoran / Kafe'), ('5411', "Oziq-ovqat do'koni / Supermarket"), ('5912', 'Dorixona / Apteka'), ('5661', "Kiyim-kechak do'koni"), ('7011', 'Mehmonxona / Hotel'), ('5571', 'Avtomobil ehtiyot qismlari'), ('5251', "Qurilish mollari do'koni"), ('8099', 'Tibbiy xizmatlar'), ('7299', "Maishiy xizmatlar (sartaroshxona, go'zallik saloni)"), ('5999', 'Boshqa chakana savdo')], max_length=10, verbose_name='MCC Kategoriya')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzunlik')),
                ('district', models.CharField(choices=[('Yunusobod', 'Yunusobod tumani'), ('Chilonzor', 'Chilonzor tumani'), ('Mirzo Ulugbek', "Mirzo Ulug'bek tumani"), ('Shayxontohur', 'Shayxontohur tumani'), ('Olmazor', 'Olmazor tumani'), ('Mirobod', 'Mirobod tumani'), ('Yakkasaroy', 'Yakkasaroy tumani'), ('Bektemir', 'Bektemir tumani'), ('Sergeli', 'Sergeli tumani'), ('Uchtepa', 'Uchtepa tumani'), ('Yashnobod', 'Yashnobod tumani'), ('Zangiota', 'Zangiota tumani')], max_length=100, verbose_name='Tuman')),
                ('address_hint', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Investitsiya (so'm)")),
                ('monthly_fixed_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Oylik doimiy xarajatlar')),
                ('variable_cost_pct', models.FloatField(default=35.0, verbose_name="O'zgaruvchi xarajatlar %")),
                ('planned_markup_pct', models.FloatField(default=40.0, verbose_name='Belgilangan ustama %')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('done', 'Tayyor'), ('failed', 'Xato')], default='pending', max_length=20)),
                ('progress_pct', models.IntegerField(default=0)),
                ('completed_blocks', models.JSONField(default=list)),
                ('warning_flag', models.BooleanField(default=False)),
                ('warning_message', models.TextField(blank=True)),
                ('final_recommendation', models.CharField(blank=True, choices=[('YES', 'HA'), ('NO', "YO'Q"), ('CAUTION', 'EHTIYOT')], max_length=10, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('final_commentary', models.TextField(blank=True)),
                ('credit_tier', models.CharField(blank=True, max_length=30)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Tahlil so'rovi",
                'verbose_name_plural': "Tahlil so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CLIENT', 'Mijoz'), ('OFFICER', 'Bank Xodimi'), ('ADMIN', 'Administrator')], default='CLIENT', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
