# Generated by Django 6.0.4 on 2026-04-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='address_detail',
            field=models.CharField(blank=True, help_text="Ko'cha, bino, mo'ljal", max_length=255, verbose_name='Batafsil manzil'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='average_check_uzs',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=12, verbose_name="O'rtacha chek (UZS)"),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='business_category',
            field=models.CharField(choices=[('food_beverage', 'Ovqat va ichimlik'), ('retail', 'Chakana savdo'), ('health_beauty', "Sog'liq va go'zallik"), ('education', "Ta'lim"), ('services', 'Xizmatlar'), ('entertainment', "Ko'ngil ochar"), ('tech', 'Texnologiya'), ('other', 'Boshqa')], default='other', max_length=50, verbose_name='Biznes kategoriyasi'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='business_description',
            field=models.TextField(blank=True, help_text='Biznes rejangiz haqida erkin yozing. Gemini bu matnni barcha bloklarga kontekst sifatida uzatadi.', verbose_name='Biznes tavsifi'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='cogs_percentage',
            field=models.FloatField(default=35.0, verbose_name='Tovar tannarxi %'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='competitor_advantage',
            field=models.TextField(blank=True, verbose_name='Raqobat ustunligi'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='desired_payback_months',
            field=models.IntegerField(default=24, verbose_name='Qaytarish muddati (oy)'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='expected_daily_customers',
            field=models.IntegerField(default=50, verbose_name='Kunlik kutilgan mijozlar soni'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='floor_area_sqm',
            field=models.FloatField(default=50.0, verbose_name='Maydon (kv.m)'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='has_seasonal_dependency',
            field=models.BooleanField(default=False, verbose_name='Mavsumiylik bor'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='known_competitors',
            field=models.TextField(blank=True, verbose_name="Ma'lum raqobatchilar"),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='loan_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Kredit miqdori (UZS)'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='location_type',
            field=models.CharField(choices=[('street_front', "Ko'cha bo'yi"), ('mall', 'Savdo markazi ichida'), ('market', 'Bozor ichida'), ('residential', 'Turar-joy massivi'), ('business_center', 'Biznes markaz'), ('standalone', 'Alohida bino')], default='street_front', max_length=50, verbose_name='Lokatsiya turi'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='market_experience_years',
            field=models.IntegerField(default=0, verbose_name='Soha tajribasi (yil)'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='monthly_rent_uzs',
            field=models.DecimalField(decimal_places=0, default=3000000, max_digits=12, verbose_name='Oylik ijara (UZS)'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='monthly_salary_budget',
            field=models.DecimalField(decimal_places=0, default=5000000, max_digits=12, verbose_name='Oylik ish haqi fondi (UZS)'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='monthly_utilities',
            field=models.DecimalField(decimal_places=0, default=500000, max_digits=12, verbose_name='Kommunal xarajatlar (UZS/oy)'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='nearby_landmarks',
            field=models.TextField(blank=True, verbose_name="Yaqin mo'ljallar"),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='num_employees',
            field=models.IntegerField(default=3, verbose_name='Xodimlar soni'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='operating_hours_end',
            field=models.TimeField(default='21:00', verbose_name='Ish tugash vaqti'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='operating_hours_start',
            field=models.TimeField(default='09:00', verbose_name='Ish boshlanish vaqti'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='own_capital',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Shaxsiy kapital (UZS)'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='parking_available',
            field=models.BooleanField(default=False, verbose_name='Avtoturargoh mavjud'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='planned_opening_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ochilish sanasi'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='previously_failed_business',
            field=models.BooleanField(default=False, verbose_name='Oldingi muvaffaqiyatsiz urinish'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='public_transport_nearby',
            field=models.BooleanField(default=True, verbose_name='Jamoat transporti yaqin'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='seasonal_notes',
            field=models.TextField(blank=True, verbose_name='Mavsumiylik izohi'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='target_customer',
            field=models.CharField(choices=[('students', 'Talabalar'), ('office_workers', 'Ofis xodimlari'), ('families', 'Oilalar'), ('tourists', 'Sayyohlar'), ('all', 'Barcha')], default='all', max_length=50, verbose_name='Maqsadli mijoz'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='unique_selling_point',
            field=models.CharField(blank=True, max_length=255, verbose_name='Raqobatchilardan farqli tomoni'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='working_days_per_week',
            field=models.IntegerField(choices=[(5, '5 kun'), (6, '6 kun'), (7, '7 kun')], default=7, verbose_name='Haftalik ish kunlari'),
        ),
        migrations.AlterField(
            model_name='businessanalysisrequest',
            name='address_hint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manzil izohi'),
        ),
        migrations.AlterField(
            model_name='businessanalysisrequest',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=50000000, max_digits=15, verbose_name="Jami investitsiya (so'm)"),
        ),
        migrations.AlterField(
            model_name='businessanalysisrequest',
            name='latitude',
            field=models.FloatField(default=41.2995, verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='businessanalysisrequest',
            name='longitude',
            field=models.FloatField(default=69.2401, verbose_name='Uzunlik'),
        ),
        migrations.AlterField(
            model_name='businessanalysisrequest',
            name='monthly_fixed_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Oylik doimiy xarajatlar (jami)'),
        ),
    ]
