# Generated by Django 6.0.4 on 2026-04-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessanalysisrequest_address_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='business_category_type',
            field=models.CharField(choices=[('general', 'Umumiy biznes'), ('hotel', 'Mehmonxona / Turizm'), ('construction', 'Qurilish'), ('textile', 'Tekstil sanoati'), ('trade', 'Savdo / Chakana')], default='general', max_length=20, verbose_name='Biznes kategoriyasi turi'),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='sqb_collateral_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='sqb_commentary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='sqb_composite_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='sqb_debt_burden_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='sqb_dsc_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='sqb_recommendation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='sqb_recommendation_color',
            field=models.CharField(blank=True, default='gray', max_length=20),
        ),
    ]
