# Generated by Django 6.0.4 on 2026-04-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businessanalysisrequest_business_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='is_24_7',
            field=models.BooleanField(default=False, verbose_name='24/7 ishlaydi'),
        ),
        migrations.AlterField(
            model_name='businessanalysisrequest',
            name='business_category_type',
            field=models.CharField(choices=[('hotel', 'Mehmonxona / Turizm'), ('construction', 'Qurilish'), ('textile', 'Tekstil sanoati'), ('trade', 'Savdo / Chakana')], default='hotel', max_length=20, verbose_name='Biznes kategoriyasi turi'),
        ),
        migrations.AlterField(
            model_name='businessanalysisrequest',
            name='operating_hours_end',
            field=models.TimeField(blank=True, default='21:00', null=True, verbose_name='Ish tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='businessanalysisrequest',
            name='operating_hours_start',
            field=models.TimeField(blank=True, default='09:00', null=True, verbose_name='Ish boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='businessanalysisrequest',
            name='target_customer',
            field=models.JSONField(default=list, verbose_name='Maqsadli mijoz'),
        ),
    ]
