# Generated by Django 6.0.4 on 2026-04-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businessanalysisrequest_external_checks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_ai_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('mock', 'Mock (Testing)')], default='gemini', max_length=20, verbose_name='Faol AI Provayderi')),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gemini API Key')),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenAI API Key')),
                ('anthropic_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anthropic API Key')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tizim Sozlamalari',
                'verbose_name_plural': 'Tizim Sozlamalari',
            },
        ),
    ]
