# Generated by Django 5.2.13 on 2026-04-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_expand_mcc_add_tourism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='active_ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('huggingface', 'HuggingFace'), ('mock', 'Mock (Testing)')], default='gemini', max_length=20, verbose_name='Faol AI Provayderi'),
        ),
    ]
