# Generated by Django 5.2.13 on 2026-04-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_huggingface_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='form_data_json',
            field=models.JSONField(blank=True, default=dict, verbose_name="Saqlangan forma ma'lumotlari"),
        ),
    ]
