# Generated by Django 6.0.4 on 2026-04-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_save_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='foot_traffic',
            field=models.CharField(choices=[('very_high', '>500 kishi/kun'), ('high', '200-500'), ('medium', '50-200'), ('low', '<50')], default='medium', max_length=20, verbose_name="Kunlik piyoda o'tuvchilar"),
        ),
    ]
