# Generated by Django 6.0.4 on 2026-04-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_businessanalysisrequest_foot_traffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='sqb_credit_product',
            field=models.CharField(choices=[('business_welcome', 'SQB Business Welcome (Onlayn kredit, 500 mln gacha)'), ('ishonch', "Ishonch krediti (Aylanma mablag', 28 mlrd gacha)"), ('investment', 'Investitsion loyihalar (Asosiy vositalar, 28 mlrd gacha)'), ('refinance', 'Refinans krediti (Boshqa bankdan qayta moliyalash, 2 mlrd gacha)')], default='ishonch', max_length=50, verbose_name='SQB Kredit Maxsuloti'),
        ),
    ]
