# Generated by Django 6.0.4 on 2026-04-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_businessanalysisrequest_sqb_credit_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zalog_id', models.CharField(max_length=50, unique=True, verbose_name='Zalog ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('property_type', models.CharField(max_length=50, verbose_name='Mulk turi')),
                ('total_value', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Umumiy qiymat (UZS)')),
            ],
            options={
                'verbose_name': 'Garov (Zalog)',
                'verbose_name_plural': 'Garovlar (Zaloglar)',
            },
        ),
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='zalog_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zalog ID'),
        ),
        migrations.AlterField(
            model_name='businessanalysisrequest',
            name='desired_payback_months',
            field=models.IntegerField(default=24, verbose_name='Qaytarish muddati'),
        ),
    ]
