# Generated by Django 6.0.4 on 2026-04-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_zalog_businessanalysisrequest_zalog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Foydalanuvchiga xabar berilganmi'),
        ),
    ]
