# Generated by Django 6.0.4 on 2026-04-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_businessanalysisrequest_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='target_monthly_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Kutilayotgan oylik daromad (UZS)'),
        ),
    ]
