# Generated by Django 5.2.13 on 2026-04-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_businessanalysisrequest_target_monthly_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessanalysisrequest',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Biznes nomi'),
        ),
    ]
