# Generated by Django 5.2.13 on 2026-04-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_businessanalysisrequest_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='aicc_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AICC API Key'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='aicc_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AICC URL'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='active_ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('huggingface', 'HuggingFace'), ('aicc', 'AI.CC (Proxy)'), ('mock', 'Mock (Testing)')], default='gemini', max_length=20, verbose_name='Faol AI Provayderi'),
        ),
    ]
