# Generated by Django 5.2.13 on 2026-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_systemconfiguration_aicc_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='apifreellm_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FreeLLM API Key'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='openrouter_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenRouter API Key'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='active_ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('anthropic', 'Claude (Anthropic)'), ('aicc', 'AI.CC Proxy'), ('openrouter', 'OpenRouter'), ('apifreellm', 'FreeLLM (Llama-3)'), ('huggingface', 'HuggingFace'), ('mock', 'Test Rejimi (Mock)')], default='gemini', max_length=20, verbose_name='Faol AI Provayderi'),
        ),
    ]
