# Generated by Django 6.0.4 on 2026-04-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tam_uzs', models.BigIntegerField(default=0, verbose_name="TAM (so'm)")),
                ('sam_uzs', models.BigIntegerField(default=0, verbose_name="SAM (so'm)")),
                ('som_uzs', models.BigIntegerField(default=0, verbose_name="SOM (so'm)")),
                ('saturation_index', models.FloatField(default=0.0)),
                ('gap_score', models.FloatField(default=0.0)),
                ('niche_opportunity_score', models.FloatField(default=0.0)),
                ('ai_commentary', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('is_mock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_a', to='core.businessanalysisrequest')),
            ],
            options={
                'verbose_name': 'A Blok — Bozor tahlili',
            },
        ),
    ]
